language: go
go: 1.11
sudo: false

before_install:
  - export PATH=/home/travis/gopath/bin:$PATH

install:
  - go get -u github.com/pressly/goose/cmd/goose
  - go get github.com/kylelemons/go-gypsy/yaml
  - go get github.com/erikstmartin/go-testdb
  - go get github.com/lib/pq

env:
  - DB=postgres GO_ENV=test
  - DB=mysql GO_ENV=test
  - DB=mock GO_ENV=test

before_script: 
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database points;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database points;'; fi"
  - sh -c "if [ '$DB' != 'mock' ]; then goose -path db/$DB -env test up; fi"

script: go test